FROM node:22
ARG RANDOM_USER_HOST

WORKDIR /App
RUN git clone https://github.com/rockyliyanlok/nextjs-randomuser-graphql.git .
RUN yarn

RUN sed -i s,https://randomuser.me,${RANDOM_USER_HOST}, ./next.config.js

EXPOSE 3000
CMD npm run dev
